version: 'build-{build}'

image: Visual Studio 2017 Preview

branches:
  only:
  - master

build_script:
- ps: dotnet restore .\src\Qmmands.sln | Out-Host
- ps: dotnet build .\src\Qmmands.sln -c "Release" --no-restore | Out-Host

after_build:
- ps: >-
    if ($Env:APPVEYOR_REPO_TAG -eq "false")
    {
       $BuildNumber = ([int] $Env:APPVEYOR_BUILD_NUMBER).ToString("00000")
       dotnet pack .\src\Qmmands -c Release -o .\..\..\artifacts --no-restore --no-build --version-suffix="nightly-$BuildNumber" | Out-Host
    }
    else
    {
        dotnet pack .\src\Qmmands -c Release -o .\..\..\artifacts --no-restore --no-build | Out-Host
    }

nuget:
  disable_publish_on_pr: true

pull_requests:
  do_not_increment_build_number: true

test: off

artifacts:
- path: .\artifacts\*.nupkg
  name: NuGet
  
deploy:
- provider: NuGet
  server: https://www.myget.org/F/qmmands/api/v2
  api_key:
    secure: XW7HgRlmPz8/YHNSCAjAzBbYvgTx1dVSA+OU8AmuU6OamtFJnUr2CCAbHukPg0r7
  skip_symbols: true
  on:
    branch: master
- provider: NuGet
  api_key:
    secure: O7xmTfASfpU1YlRDxaLRtK0Nkjt6T03B6K4oT96B32mNTw7K0ZbC7c8/dxe9yTqW
  on:
    branch: master
    appveyor_repo_tag: true